ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
        host = ${?HOST}
    }
    application {
        modules = [ website.woodendoor.conflux.ApplicationKt.module ]
    }
}

database {
    driver = "org.h2.Driver"
    driver = ${?DB_DRIVER}
    url = "jdbc:h2:mem:conflux;DB_CLOSE_DELAY=-1;"
    url = ${?DB_URL}
}
